# Generated by Django 5.2.1 on 2025-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=12345, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
