# Generated by Django 5.2.1 on 2025-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(editable=False),
        ),
    ]
