# Generated by Django 5.2.1 on 2025-05-29 05:01

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=tasks.models.generate_task_id, editable=False, max_length=5, unique=True),
        ),
    ]
